import Link from "next/link";
import { SiteHeader } from "@/components/SiteHeader";
import { Footer } from "@/components/Footer";
import { ProductCard } from "@/components/ProductCard";
import { getPublishedProducts } from "@/lib/catalog";

export default async function Home() {
  const products = await getPublishedProducts();
  return <><SiteHeader /><main>
    <section className="hero">
      <div className="hero-copy"><p className="kicker">THE AI-ASSISTED BEAUTY MARKETPLACE</p><h1>You take care of beauty. <em>AI builds your product listings.</em></h1><p>Upload a product photo, add price and stock, and GlowMarket AI prepares the title, description, benefits, tags, and category for your approval.</p><div className="button-row"><Link className="button button-dark" href="/register">Create your beauty store</Link><Link className="button button-light" href="/marketplace">Shop the marketplace</Link></div><div className="trust-row"><span>✓ Photo-to-listing AI</span><span>✓ 10% when you sell</span><span>✓ Seller approves every listing</span></div></div>
      <div className="hero-visual"><div className="arch"><div className="hero-bottle"><span>GlowMarket</span><i /></div><div className="orb orb-one"/><div className="orb orb-two"/></div><aside><b>01</b><span>Scalp renewal oil<br/><small>by Atelier Strand</small></span></aside></div>
    </section>
    <section className="statement"><p>BUILT FOR INDEPENDENT BEAUTY BUSINESSES</p><h2>Your expertise.<br/><em>Your store, without the technical work.</em></h2></section>
    <section className="featured"><div className="section-title"><div><p className="kicker">FROM VERIFIED BEAUTY BUSINESSES</p><h2>Beauty products</h2></div><Link href="/marketplace">Explore all products →</Link></div>{products.length?<div className="product-grid">{products.slice(0,4).map(product => <ProductCard key={product.id} product={product}/>)}</div>:<div className="empty-catalog"><h3>Beauty products are coming soon.</h3><p>Verified sellers can publish their first products from the dashboard.</p></div>}</section>
    <section id="how" className="how"><div><p className="kicker">A SMALL, CLEAR WORKFLOW</p><h2>Photo in.<br/>Product listing out.</h2></div><ol><li><b>01</b><div><h3>Upload one product photo</h3><p>Add only the price, stock, and any short note AI should know.</p></div></li><li><b>02</b><div><h3>AI creates the listing</h3><p>GlowMarket prepares the title, description, benefits, tags, and beauty category.</p></div></li><li><b>03</b><div><h3>Review and publish</h3><p>Check the AI draft, approve it, and publish it to your store.</p></div></li></ol></section>
    <section id="pricing" className="seller-pricing"><div className="pricing-intro"><p className="kicker">SIMPLE MVP PRICING</p><h2>No monthly fee to open your store.</h2><p>AI listing creation is included during MVP testing. GlowMarket earns when your products sell.</p></div><div className="pricing-cards"><article><span>MARKETPLACE SALES</span><strong>10%</strong><h3>of product sales</h3><p>Customers pay delivery costs, and GlowMarket does not take commission from shipping.</p><div className="fee-example"><small>Example product sale</small><b>500 SEK</b><i>GlowMarket fee: 50 SEK</i><i>Business receives: 450 SEK</i></div></article><article><span>MVP TESTING</span><strong>Included</strong><h3>GlowMarket AI</h3><p>Upload product facts and a photo. AI creates the professional listing for your review.</p><ul><li>No AI subscription system yet</li><li>Seller review before publishing</li><li>Beauty-specific categories and tags</li></ul></article></div></section>
    <section id="salons" className="salon-cta"><p className="kicker">FOR BEAUTY BUSINESS OWNERS</p><h2>Upload the photo.<br/><em>Let AI handle the listing.</em></h2><p>Spend less time typing product information and more time running your beauty business.</p><Link className="button button-cream" href="/register">Create your beauty store</Link><div className="mini-proof"><span>Simple seller signup</span><span>AI-created listings</span><span>Beauty-specific discovery</span></div></section>
  </main><Footer /></>;
}
