"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { formatSek } from "@/lib/demo-data";

type Item = { name: string; price: number; stock: number; status: string };
const initial: Item[] = [{name:"Hydration ritual set",price:549,stock:18,status:"Live"},{name:"Bond repair mask",price:399,stock:7,status:"Live"},{name:"Daily moisture shampoo",price:279,stock:0,status:"Draft"}];
export function DashboardClient() {
  const [items,setItems]=useState(initial); const [open,setOpen]=useState(false);
  function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setItems([{name:String(f.get("name")),price:Number(f.get("price")),stock:Number(f.get("stock")),status:"Live"},...items]);setOpen(false)}
  return <div className="dash-shell"><aside className="dash-nav"><Link className="brand" href="/"><span>G</span> GlowMarket</Link><p>SALON ADMIN</p><nav><a className="selected">▦ Overview</a><a>◇ Products</a><a>▤ Orders</a><a>⌁ Storefront</a><a>⚙ Settings</a></nav><div className="salon-user"><i>NG</i><span><b>Nordic Glow</b><small>Owner account</small></span></div></aside><main className="dashboard"><header><div><p className="kicker">TUESDAY, 18 AUGUST</p><h1>Good morning, Lina.</h1></div><button className="button button-dark" onClick={()=>setOpen(true)}>+ Add product</button></header><div className="notice"><b>✓ Business profile ready</b><span>Your storefront is visible. Complete payout setup before accepting your first order.</span><button>Set up payouts →</button></div><section className="metrics"><div><span>Gross sales</span><b>12 840 kr</b><small>↑ 18% this month</small></div><div><span>Orders</span><b>31</b><small>↑ 6 this month</small></div><div><span>Products live</span><b>{items.filter(x=>x.status==='Live').length}</b><small>{items.filter(x=>!x.stock).length} needs attention</small></div><div><span>Store views</span><b>824</b><small>↑ 12% this month</small></div></section><section className="dash-card"><div className="card-head"><div><h2>Your products</h2><p>Manage what customers see in your storefront.</p></div><button onClick={()=>setOpen(true)}>Add new →</button></div><div className="product-table"><div className="table-row table-labels"><span>PRODUCT</span><span>PRICE</span><span>STOCK</span><span>STATUS</span></div>{items.map((item,i)=><div className="table-row" key={item.name+i}><span><i style={{background:`hsl(${25+i*20} 25% ${80-i*5}%)`}}/><b>{item.name}</b></span><span>{formatSek(item.price)}</span><span className={item.stock===0?"danger":""}>{item.stock || "Out of stock"}</span><span><em className={item.status.toLowerCase()}>{item.status}</em></span></div>)}</div></section></main>{open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="modal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setOpen(false)}>×</button><p className="kicker">NEW PRODUCT</p><h2>Add to your shelf</h2><label>Product name<input name="name" required placeholder="e.g. Curl definition cream"/></label><div className="field-row"><label>Price (SEK)<input name="price" type="number" min="1" required/></label><label>Stock<input name="stock" type="number" min="0" required/></label></div><label>Description<textarea required placeholder="What makes this product special?"/></label><button className="button button-dark full">Publish product</button></form></div>}</div>
}
