"use client";
import{FormEvent,useEffect,useState}from"react";import Link from"next/link";import{AIProductBuilder}from"@/components/AIProductBuilder";
type LocalStore={name:string;email:string;description:string;address:string;city:string};
const navigation=["Overview","Products","Orders","Inventory","AI Studio","Business Profile"];
export function DashboardClient(){const[builderOpen,setBuilderOpen]=useState(false);const[selected,setSelected]=useState("Overview");const[store,setStore]=useState<LocalStore|null>(null);const[productCount,setProductCount]=useState(0);
useEffect(()=>{const timer=window.setTimeout(()=>{const saved=localStorage.getItem("glowmarket-local-store");if(saved)setStore(JSON.parse(saved));setProductCount(JSON.parse(localStorage.getItem("glowmarket-local-products")||"[]").length)},0);return()=>clearTimeout(timer)},[]);
function saveStore(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const next={name:String(data.get("name")),email:String(data.get("email")),description:String(data.get("description")),address:String(data.get("address")),city:String(data.get("city"))};localStorage.setItem("glowmarket-local-store",JSON.stringify(next));setStore(next);setSelected("Overview")}
const refreshProducts=()=>setProductCount(JSON.parse(localStorage.getItem("glowmarket-local-products")||"[]").length);
return <div className="dash-shell"><aside className="dash-nav"><Link className="brand" href="/"><span>G</span> GlowMarket</Link><p>SELLER DASHBOARD</p><nav>{navigation.map(item=><button key={item} className={selected===item?"selected":""} onClick={()=>{setSelected(item);if(item==="AI Studio")setBuilderOpen(true)}}>{item}</button>)}</nav><div className="salon-user"><i>{store?.name.slice(0,2).toUpperCase()||"LS"}</i><span><b>{store?.name||"Local store"}</b><small>Development seller</small></span></div></aside><main className="dashboard"><header><div><p className="kicker">LOCAL SELLER WORKSPACE</p><h1>{selected}</h1></div>{store&&<button className="button button-dark" onClick={()=>setBuilderOpen(true)}>+ Build product with AI</button>}</header><div className="notice"><b>Development mode</b><span>Business verification is preserved but bypassed locally. Production sellers still require verification.</span></div>{(!store||selected==="Business Profile")?<section className="dash-card local-store-setup"><p className="kicker">LOCAL STORE SETUP</p><h2>{store?"Edit your test store":"Create your test store"}</h2><p>This stays only in your browser and lets you test the seller workflow before the verification API is connected.</p><form onSubmit={saveStore}><div className="field-row"><label>Store name<input name="name" required defaultValue={store?.name}/></label><label>Seller email<input name="email" type="email" required defaultValue={store?.email}/></label></div><label>Store description<textarea name="description" required defaultValue={store?.description}/></label><div className="field-row"><label>Dispatch address<input name="address" required defaultValue={store?.address}/></label><label>City<input name="city" required defaultValue={store?.city}/></label></div><button className="button button-dark">Save local store</button></form></section>:<><section className="metrics"><div><span>Products</span><b>{productCount}</b><small>Local product drafts</small></div><div><span>Orders</span><b>0</b><small>No test orders</small></div><div><span>Low stock</span><b>0</b><small>Inventory clear</small></div><div><span>Store</span><b>Ready</b><small>{store.name}</small></div></section><section className="dash-card dashboard-empty"><p className="kicker">AI PRODUCT BUILDER</p><h2>Create your first product draft.</h2><p>AI uses only the product facts you provide. Review and edit the result before saving.</p><button className="button button-dark" onClick={()=>setBuilderOpen(true)}>Create product draft</button></section></> }</main>{builderOpen&&<AIProductBuilder onClose={()=>setBuilderOpen(false)} onLocalProductSaved={refreshProducts}/>}</div>}
